variable "region" {}
variable "access_key" {}
variable "secret_key" {}
variable "vpc_cidr" {}
variable "ami_wordpress" {}
variable "project_name" {}
variable "public_subnet_1a" {}
variable "public_subnet_1b" {}
variable "private_subnet_1a_app" {}
variable "private_subnet_1b_app" {}
variable "private_subnet_1a_data" {}
variable "private_subnet_1b_data" {}
variable "password" {}
